### ISSUE TITLE
config:publish command doesn't work

### ISSUE THREAD

**Issue by fede91it** [rephluX/laravel-pagetitle#5]
The command you suggest to use to generate the default configuration file doesn't work on Laravel 5.2

`php artisan config:publish rephlux/pagetitle`

**Comment by MujibAzizi** [comment]
Hi, 

You can do  `php artisan vendor:publish --provider="Rephlux\PageTitle\PageTitleServiceProvider"`.

**Comment by fede91it** [comment]
Thank you. Why the suggested command doesn't work?

**Comment by MujibAzizi** [comment]
Because in Laravel 5 the command to publish the config for an package has changed.

**Comment by rephluX** [comment]
Yes, the publish command was still a old one. Thanks for giving me a hint that the readme was not up to date. I've just updated the readme with the new publish command and some other minor changes.
