### ISSUE TITLE
Possibility to set the config values later

### ISSUE THREAD

**Issue by DevDaveo** [rephluX/laravel-pagetitle#7]
My page name has a dynamic part in it's name (depending on the country it's used in).
Is there any chance to alter the config values in another ServiceProvider for example?
Having public setters on the PageTitle class would be great!

**Comment by rephluX** [comment]
Yes, i've just added setter and getter methods for the initial config values. Please use the latest version v0.9 to user that feature. Check the updated readme how to use the new methods.
